"""add_user_model_and_link_to_team

Revision ID: 9d66d62393de
Revises: 
Create Date: 2025-12-22 06:11:22.577157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d66d62393de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_id', sa.Integer(), nullable=True, comment='ID đại diện đội (User)'))
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_foreign_key(None, 'teams', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_column('teams', 'user_id')
    # ### end Alembic commands ###

